apiVersion: v1
kind: Service
metadata:
  name: capstone-service
spec:
  type: NodePort
  selector:
    app: capstone
  ports:
  - name: Container ports
    port: 8080
    targetPort: 8080
    NodePort: 30008
